--select count(*) from EMC.dbo.account;
--select count(*) from dbo.account where gender='1';
--select count(*) from dbo.account where yearofbirth < '1979';
-- select count(*) from dbo.account where grade=2013;
